# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - name: Install SSH
      uses: webfactory/ssh-agent@v0.4.1
      with :
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        SSH: true
        BRANCH: gh-pages
        FOLDER: build
        CLEAN: true
